name: Test YouTube Shorts Generator

on:
  workflow_dispatch:
    inputs:
      youtube_url:
        description: 'YouTube Video URL to test'
        required: true
        type: string
        default: 'https://www.youtube.com/watch?v=jNQXAC9IVRw'

jobs:
  test-system:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run basic tests
      run: |
        python test.py
    
    - name: Test with sample video
      run: |
        python main.py --url "${{ github.event.inputs.youtube_url }}"
    
    - name: Upload generated shorts
      uses: actions/upload-artifact@v4
      with:
        name: test-shorts
        path: generated_shorts/
        retention-days: 7
    
    - name: Test web app
      run: |
        python -c "from web_app import app; print('Web app imports successfully')"
